# Generated by Django 2.0 on 2019-05-28 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('facility_name', models.CharField(max_length=100)),
                ('price', models.BigIntegerField()),
                ('buyer', models.CharField(max_length=100)),
                ('buy_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.DateField(auto_now=True)),
                ('staff_name', models.CharField(max_length=100)),
                ('complmentary', models.TextField()),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baoxiu_staff_name', models.CharField(max_length=100)),
                ('baoxiu_staff_id', models.IntegerField()),
                ('baoxiu_time', models.DateField(auto_now=True)),
                ('baoxiu_complementary', models.CharField(max_length=200)),
                ('repair_staff_id', models.IntegerField()),
                ('repair_staff_name', models.CharField(max_length=100)),
                ('repair_time', models.DateField(auto_now=True)),
                ('repair_complementary', models.CharField(max_length=200)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility')),
            ],
        ),
    ]
