# Generated by Django 2.0 on 2019-05-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='baoxiu_staff_id',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='repair_staff_id',
        ),
        migrations.AlterField(
            model_name='facility',
            name='buy_time',
            field=models.DateField(auto_now_add=True, verbose_name='购买时间'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='buyer',
            field=models.CharField(max_length=100, verbose_name='购买人'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='price',
            field=models.BigIntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='version',
            field=models.CharField(max_length=100, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='complmentary',
            field=models.TextField(verbose_name='补充'),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='last_time',
            field=models.DateField(auto_now=True, verbose_name='保养时间'),
        ),
        migrations.AlterField(
            model_name='maintain',
            name='staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repair',
            name='baoxiu_complementary',
            field=models.CharField(max_length=200, verbose_name='保修描述'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='baoxiu_staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='保修人'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='baoxiu_time',
            field=models.DateField(auto_now=True, verbose_name='保修时间'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_complementary',
            field=models.CharField(max_length=200, verbose_name='维修补充'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_staff_name',
            field=models.CharField(max_length=100, verbose_name='维修人'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='repair_time',
            field=models.DateField(auto_now=True, verbose_name='维修时间'),
        ),
    ]
