# Generated by Django 2.0 on 2019-05-28 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_auto_20190528_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baoxiu',
            name='baoxiu_staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='报修人'),
        ),
    ]
