# Generated by Django 2.0 on 2019-06-02 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_auto_20190601_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='baoxiu_place',
        ),
        migrations.AddField(
            model_name='repair',
            name='baoxiu_staff_tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='repair',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facility.Facility', verbose_name='故障设备'),
        ),
    ]
