# Generated by Django 2.0 on 2019-06-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0006_auto_20190602_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='baoxiu_complementary',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='报修描述'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='baoxiu_time',
            field=models.DateField(auto_now=True, null=True, verbose_name='报修时间'),
        ),
    ]
