# Generated by Django 2.0 on 2019-06-02 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0008_auto_20190602_1056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['-baoxiu_time']},
        ),
    ]
