# Generated by Django 2.0 on 2019-06-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0010_remove_repair_repair_complementary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['baoxiu_time']},
        ),
    ]
