# Generated by Django 2.0 on 2019-06-05 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0014_auto_20190605_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='购买人'),
        ),
    ]
