# Generated by Django 2.0 on 2019-05-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True)),
                ('luosi_num', models.IntegerField(default=0)),
                ('luosi_change', models.IntegerField(default=0)),
                ('luomu_num', models.IntegerField(default=0)),
                ('luomu_change', models.IntegerField(default=0)),
                ('product1_num', models.IntegerField(default=0)),
                ('product1_change', models.IntegerField(default=0)),
            ],
        ),
    ]
