# Generated by Django 2.0 on 2019-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='luomu_change',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='luosi_change',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product1_change',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='current_time',
            field=models.DateField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='luomu_num',
            field=models.IntegerField(default=0, verbose_name='螺母'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='luosi_num',
            field=models.IntegerField(default=0, verbose_name='螺丝'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product1_num',
            field=models.IntegerField(default=0, verbose_name='产品一'),
        ),
    ]
