# Generated by Django 2.0 on 2019-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20190528_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100, verbose_name='品名')),
                ('good_version', models.CharField(max_length=100, verbose_name='型号')),
                ('good_num', models.IntegerField(default=0, verbose_name='数量')),
                ('apply_staff_name', models.CharField(max_length=100, verbose_name='申请人')),
                ('apply_date', models.DateField(auto_now_add=True, verbose_name='申请日期')),
                ('sanction_staff_name', models.CharField(max_length=100, verbose_name='批准人')),
                ('sanction_date', models.DateField(auto_now_add=True, verbose_name='批准日期')),
                ('buyer_name', models.DateField(auto_now_add=True, verbose_name='采购员')),
                ('buyer_date', models.DateField(auto_now_add=True, verbose_name='采购日期')),
                ('price', models.BigIntegerField(default=0, verbose_name='单价')),
                ('total_price', models.BigIntegerField(default=0, verbose_name='总价')),
            ],
        ),
    ]
