# Generated by Django 2.0 on 2019-05-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20190528_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producediary',
            name='facility_id',
        ),
    ]
