# Generated by Django 2.0 on 2019-05-28 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
        ('warehouse', '0005_remove_producediary_facility_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producediary',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facility.Facility', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='apply_staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
    ]
