# Generated by Django 2.0 on 2019-05-28 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_auto_20190528_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselist',
            name='good_name',
        ),
        migrations.RemoveField(
            model_name='purchaselist',
            name='good_num',
        ),
        migrations.RemoveField(
            model_name='purchaselist',
            name='good_version',
        ),
        migrations.RemoveField(
            model_name='purchaselistsanction',
            name='good_name',
        ),
        migrations.RemoveField(
            model_name='purchaselistsanction',
            name='good_num',
        ),
        migrations.RemoveField(
            model_name='purchaselistsanction',
            name='good_version',
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='buyer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AlterField(
            model_name='purchaselistsanction',
            name='sanction_staff_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
    ]
