# Generated by Django 2.0 on 2019-05-30 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0010_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producediary',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.Product', verbose_name='产品'),
        ),
    ]
