# Generated by Django 2.0 on 2019-06-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_auto_20190530_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselist',
            name='PurchaseList_id',
        ),
        migrations.RemoveField(
            model_name='purchaselist',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='purchaselistapply',
            name='apply_staff_name',
        ),
        migrations.RemoveField(
            model_name='purchaselistsanction',
            name='PurchaseList_sanction_id',
        ),
        migrations.RemoveField(
            model_name='purchaselistsanction',
            name='sanction_staff_name',
        ),
        migrations.DeleteModel(
            name='PurchaseList',
        ),
        migrations.DeleteModel(
            name='PurchaseListApply',
        ),
        migrations.DeleteModel(
            name='PurchaseListSanction',
        ),
    ]
