# Generated by Django 2.0 on 2019-06-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_purchaselist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaselist',
            name='apply_staff_name',
        ),
        migrations.RemoveField(
            model_name='purchaselist',
            name='buyer_name',
        ),
        migrations.RemoveField(
            model_name='purchaselist',
            name='sanction_staff_name',
        ),
        migrations.DeleteModel(
            name='PurchaseList',
        ),
    ]
