# Generated by Django 2.0 on 2019-06-06 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0016_goods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producediary',
            options={'ordering': ['-current_time']},
        ),
        migrations.AlterModelOptions(
            name='purchaselist',
            options={'ordering': ['-apply_date']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-current_time']},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='luomu_num',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='luosi_num',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product1_num',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='number',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.Product', verbose_name='产品类型'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='unit',
            field=models.IntegerField(null=True, verbose_name='单位'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='apply_staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_a', to=settings.AUTH_USER_MODEL, verbose_name='申请人'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='buyer_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='采购日期'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='buyer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='purchase_c', to=settings.AUTH_USER_MODEL, verbose_name='采购员'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='单价'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='sanction_date',
            field=models.DateField(auto_now=True, null=True, verbose_name='批准日期'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='sanction_staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_b', to=settings.AUTH_USER_MODEL, verbose_name='批准人'),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='total_price',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='总价'),
        ),
    ]
