# Generated by Django 2.0 on 2019-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0017_auto_20190606_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='number',
            field=models.CharField(max_length=100, null=True, verbose_name='数量'),
        ),
    ]
