# Generated by Django 2.0 on 2019-06-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0018_auto_20190607_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='number',
            field=models.IntegerField(null=True, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='unit',
            field=models.CharField(max_length=10, null=True, verbose_name='单位'),
        ),
    ]
