# Generated by Django 2.0 on 2019-06-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0019_auto_20190607_0032'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('number', models.IntegerField(null=True, verbose_name='数量')),
                ('unit', models.CharField(max_length=10, null=True, verbose_name='单位')),
                ('source_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.Goods', verbose_name='原料类型')),
            ],
            options={
                'ordering': ['-current_time'],
            },
        ),
    ]
