# Generated by Django 2.0 on 2019-06-07 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0020_warehousesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producediary',
            name='facility_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facility.Facility', verbose_name='设备'),
        ),
    ]
