# Generated by Django 2.0 on 2019-06-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20190530_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='notice',
            name='created_time',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='发布时间'),
        ),
    ]
