# Generated by Django 2.0 on 2019-06-02 03:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_auto_20190602_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='发布时间'),
            preserve_default=False,
        ),
    ]
