# Generated by Django 2.0 on 2019-05-27 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=10, verbose_name='性别')),
                ('staff_age', models.PositiveIntegerField(verbose_name='年龄')),
                ('staff_home', models.CharField(max_length=100, verbose_name='籍贯')),
                ('staff_nationality', models.CharField(max_length=20, verbose_name='民族')),
                ('staff_tel', models.BigIntegerField(verbose_name='电话')),
                ('start_time', models.DateField(auto_now_add=True, verbose_name='入职时间')),
                ('id_card', models.CharField(max_length=20, verbose_name='身份证')),
                ('staff_type', models.CharField(max_length=100, verbose_name='职位')),
                ('salary_pre_hour', models.IntegerField(verbose_name='时薪')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
