# Generated by Django 2.0 on 2019-05-28 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='日期')),
                ('flag_leave', models.BooleanField(default=False, verbose_name='请假')),
                ('flag_business', models.BooleanField(default=False, verbose_name='出差')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='上班时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, verbose_name='下班时间')),
                ('supplement', models.CharField(max_length=100, verbose_name='补充')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True, verbose_name='时间')),
                ('attend_days', models.IntegerField(default=0, verbose_name='出勤')),
                ('leave_days', models.IntegerField(default=0, verbose_name='请假')),
                ('absent_days', models.IntegerField(default=0, verbose_name='旷班')),
                ('business_days', models.IntegerField(default=0, verbose_name='出差')),
                ('late_days', models.IntegerField(default=0, verbose_name='迟到')),
                ('overtime', models.IntegerField(default=0, verbose_name='加班时长')),
                ('base_salary', models.IntegerField(default=0, verbose_name='基础工资')),
                ('overtime_salary', models.IntegerField(default=0, verbose_name='加班工资')),
                ('kouchu', models.IntegerField(default=0, verbose_name='应扣')),
                ('allowance', models.IntegerField(default=0, verbose_name='补贴')),
                ('should_pay', models.IntegerField(default=0, verbose_name='应发')),
                ('tax', models.IntegerField(default=0, verbose_name='个人所得税')),
                ('actual_pay', models.IntegerField(default=0, verbose_name='实发')),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
        ),
    ]
