# Generated by Django 2.0 on 2019-05-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_attendance_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='下班时间'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='supplement',
            field=models.CharField(max_length=100, null=True, verbose_name='补充'),
        ),
    ]
