# Generated by Django 2.0 on 2019-05-28 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190528_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下班时间'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='supplement',
            field=models.CharField(default='无', max_length=100, null=True, verbose_name='补充'),
        ),
    ]
