# Generated by Django 2.0 on 2019-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190528_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='leave_days',
            field=models.IntegerField(verbose_name='请假'),
        ),
    ]
