# Generated by Django 2.0 on 2019-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190528_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='absent_days',
            field=models.IntegerField(verbose_name='旷班'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='attend_days',
            field=models.IntegerField(verbose_name='出勤'),
        ),
    ]
