# Generated by Django 2.0 on 2019-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190528_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='actual_pay',
            field=models.IntegerField(verbose_name='实发'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='allowance',
            field=models.IntegerField(verbose_name='补贴'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.IntegerField(verbose_name='基础工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='business_days',
            field=models.IntegerField(verbose_name='出差'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='kouchu',
            field=models.IntegerField(verbose_name='应扣'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='late_days',
            field=models.IntegerField(verbose_name='迟到'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.IntegerField(verbose_name='加班时长'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_salary',
            field=models.IntegerField(verbose_name='加班工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='should_pay',
            field=models.IntegerField(verbose_name='应发'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.IntegerField(verbose_name='个人所得税'),
        ),
    ]
