# Generated by Django 2.0 on 2019-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190528_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_tel',
            field=models.BigIntegerField(verbose_name='电话'),
        ),
    ]
