# Generated by Django 2.0 on 2019-06-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-current_time']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-current_time']},
        ),
    ]
