# Generated by Django 2.0 on 2019-06-02 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20190602_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.Position', verbose_name='职位'),
        ),
    ]
