# Generated by Django 2.0 on 2019-06-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20190602_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(auto_now=True, verbose_name='下班时间'),
        ),
    ]
