# Generated by Django 2.0 on 2019-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20190605_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='zaotui_days',
            field=models.IntegerField(default=0, verbose_name='早退'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='absent_days',
            field=models.IntegerField(default=0, verbose_name='旷班'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='actual_pay',
            field=models.IntegerField(default=0, verbose_name='实发'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='allowance',
            field=models.IntegerField(default=0, verbose_name='补贴'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='attend_days',
            field=models.IntegerField(default=0, verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.IntegerField(default=0, verbose_name='基础工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='business_days',
            field=models.IntegerField(default=0, verbose_name='出差'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='kouchu',
            field=models.IntegerField(default=0, verbose_name='应扣'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='late_days',
            field=models.IntegerField(default=0, verbose_name='迟到'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='leave_days',
            field=models.IntegerField(default=0, verbose_name='请假'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.IntegerField(default=0, verbose_name='加班时长'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_salary',
            field=models.IntegerField(default=0, verbose_name='加班工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='should_pay',
            field=models.IntegerField(default=0, verbose_name='应发'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.IntegerField(default=0, verbose_name='个人所得税'),
        ),
    ]
