# Generated by Django 2.0 on 2019-06-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20190606_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='supplement',
            field=models.CharField(blank=True, default='无', max_length=100, null=True, verbose_name='补充'),
        ),
    ]
