# Generated by Django 2.0 on 2019-06-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20190606_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='zaotui_days',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='supplement',
            field=models.CharField(default='无', max_length=100, null=True, verbose_name='补充'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='absent_days',
            field=models.IntegerField(verbose_name='旷班'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='actual_pay',
            field=models.IntegerField(verbose_name='实发'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='allowance',
            field=models.IntegerField(verbose_name='补贴'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='attend_days',
            field=models.IntegerField(verbose_name='出勤'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='base_salary',
            field=models.IntegerField(verbose_name='基础工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='business_days',
            field=models.IntegerField(verbose_name='出差'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='kouchu',
            field=models.IntegerField(verbose_name='应扣'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='late_days',
            field=models.IntegerField(verbose_name='迟到'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='leave_days',
            field=models.IntegerField(verbose_name='请假'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime',
            field=models.IntegerField(verbose_name='加班时长'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='overtime_salary',
            field=models.IntegerField(verbose_name='加班工资'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='should_pay',
            field=models.IntegerField(verbose_name='应发'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax',
            field=models.IntegerField(verbose_name='个人所得税'),
        ),
    ]
