# Generated by Django 2.0 on 2019-06-09 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190606_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='staff_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Position', verbose_name='职位'),
        ),
    ]
