# Generated by Django 2.0 on 2019-05-27 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ID', models.BigIntegerField()),
                ('order_type', models.CharField(max_length=100)),
                ('order_client', models.CharField(max_length=100)),
                ('order_time', models.DateField(auto_now_add=True)),
                ('order_end', models.DateField()),
                ('order_finish', models.DateField()),
                ('order_price', models.BigIntegerField()),
                ('order_number', models.BigIntegerField()),
                ('order_supplement', models.TextField()),
            ],
        ),
    ]
