# Generated by Django 2.0 on 2019-05-28 05:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_finish',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_type',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='产品名称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_ID',
            field=models.BigIntegerField(verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_client',
            field=models.CharField(max_length=100, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_end',
            field=models.DateField(auto_now_add=True, verbose_name='交货时间'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.BigIntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_price',
            field=models.BigIntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_supplement',
            field=models.TextField(verbose_name='补充'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_time',
            field=models.DateField(auto_now_add=True, verbose_name='订货时间'),
        ),
    ]
