# Generated by Django 2.0 on 2019-05-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190528_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_total_price',
            field=models.IntegerField(default=-1, verbose_name='总价'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_price',
            field=models.IntegerField(verbose_name='单价'),
        ),
    ]
