# Generated by Django 2.0 on 2019-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190528_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_total_price',
            field=models.IntegerField(verbose_name='总价'),
        ),
    ]
