# Generated by Django 2.0 on 2019-05-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20190528_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_ID',
        ),
    ]
