# Generated by Django 2.0 on 2019-06-05 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '__first__'),
        ('orders', '0007_auto_20190602_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='warehouse.Product', verbose_name='产品名称'),
        ),
    ]
