# Generated by Django 2.0 on 2019-06-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190605_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_supplement',
            field=models.TextField(null=True, verbose_name='补充'),
        ),
    ]
