# Generated by Django 2.0 on 2019-06-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190605_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_supplement',
            field=models.TextField(blank=True, null=True, verbose_name='补充'),
        ),
    ]
